### PR TITLE
Normalize memory and disk values to MB

### LINKED ISSUE #230: Exception when trying to display System information in R20.0.0 B3
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Upgrade to R20.0.0  Beta 3
2.  Display System via /settings/admin/serverinfo
3.

### Expected behaviour
Display of system service information

### Actual behaviour
Exception

### Server configuration

**Operating system:**   Debian

**Web server:**  Apache

**Database:**

**PHP version:**  7.3

**Nextcloud version:** (see Nextcloud admin page)  R20.0.0 B3

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated

**Where did you install Nextcloud from:** 

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**   Chrome

**Operating system:**   Windows 7

#### Web server error log
<details>
{"reqId":"v19RoxLLjoQRM7LfbESI","level":3,"time":"September 03, 2020 19:23:04","remoteAddr":"86.169.132.27","user":"xxxxxxx","app":"index","method":"GET","url":"/settings/admin/serverinfo","message":{"Exception":"Exception","Message":"Argument 1 passed to OCA\\ServerInfo\\Resources\\Disk::setUsed() must be of the type int, float given, called in /var/www/nextcloud/apps/serverinfo/lib/OperatingSystems/DefaultOs.php on line 219","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":152,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Settings\\Controller\\AdminSettingsController"},"index"]},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":308,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Settings\\Controller\\AdminSettingsController","index",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"section":"serverinfo","action":null,"_route":"settings.AdminSettings.index"}]},{"file":"/var/www/nextcloud/lib/base.php","line":1009,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/settings/admin/serverinfo"]},{"file":"/var/www/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","Line":110,"Previous":{"Exception":"TypeError","Message":"Argument 1 passed to OCA\\ServerInfo\\Resources\\Disk::setUsed() must be of the type int, float given, called in /var/www/nextcloud/apps/serverinfo/lib/OperatingSystems/DefaultOs.php on line 219","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/serverinfo/lib/OperatingSystems/DefaultOs.php","line":219,"function":"setUsed","class":"OCA\\ServerInfo\\Resources\\Disk","type":"->","args":[138893479936]},{"file":"/var/www/nextcloud/apps/serverinfo/lib/Os.php","line":95,"function":"getDiskInfo","class":"OCA\\ServerInfo\\OperatingSystems\\DefaultOs","type":"->","args":[]},{"file":"/var/www/nextcloud/apps/serverinfo/lib/Settings/AdminSettings.php","line":109,"function":"getDiskInfo","class":"OCA\\ServerInfo\\Os","type":"->","args":[]},{"file":"/var/www/nextcloud/apps/settings/lib/Controller/CommonSettingsTrait.php","line":141,"function":"getForm","class":"OCA\\ServerInfo\\Settings\\AdminSettings","type":"->","args":[]},{"file":"/var/www/nextcloud/apps/settings/lib/Controller/AdminSettingsController.php","line":83,"function":"formatSettings","class":"OCA\\Settings\\Controller\\AdminSettingsController","type":"->","args":[[[{"__class__":"OCA\\ServerInfo\\Settings\\AdminSettings"}]]]},{"file":"/var/www/nextcloud/apps/settings/lib/Controller/CommonSettingsTrait.php","line":152,"function":"getSettings","class":"OCA\\Settings\\Controller\\AdminSettingsController","type":"->","args":["serverinfo"]},{"file":"/var/www/nextcloud/apps/settings/lib/Controller/AdminSettingsController.php","line":68,"function":"getIndexResponse","class":"OCA\\Settings\\Controller\\AdminSettingsController","type":"->","args":["admin","serverinfo"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":169,"function":"index","class":"OCA\\Settings\\Controller\\AdminSettingsController","type":"->","args":["serverinfo"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Settings\\Controller\\AdminSettingsController"},"index"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":152,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Settings\\Controller\\AdminSettingsController"},"index"]},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":308,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Settings\\Controller\\AdminSettingsController","index",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"section":"serverinfo","action":null,"_route":"settings.AdminSettings.index"}]},{"file":"/var/www/nextcloud/lib/base.php","line":1009,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/settings/admin/serverinfo"]},{"file":"/var/www/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/nextcloud/apps/serverinfo/lib/Resources/Disk.php","Line":56},"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36","version":"20.0.0.5"}

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

### PR DESCRIPTION
**Pull request by kesselb**
Close #230 

`Argument 1 passed to OCA\\ServerInfo\\Resources\\Disk::setUsed() must be of the type int, float given`

Disk and Memory objects are strictly typed. That's a problem if you are using more than 2147483647 bytes on a 32 bit system. To workaround this issue I changed the units to MB and normalize the values before.  As hardening the last call is always `(int)`.

### CODE REVIEW

File: lib/OperatingSystems/DefaultOs.php [hunk 1]
```diff
@@ -195,7 +191,7 @@ public function getDiskInfo(): array {
 		$data = [];
 
 		try {
-			$disks = $this->executeCommand('df -TP');
+			$disks = $this->executeCommand('df -TPk');
```
Comment (kesselb) [inline lib/OperatingSystems/DefaultOs.php:194]: `-k` = `--block-size=1K` which is the default on most linux systems.

File: lib/OperatingSystems/FreeBSD.php [hunk 2]
```diff
@@ -53,8 +53,8 @@ public function getMemory(): Memory {
 
 		$result = preg_match_all($pattern, $swapinfo, $matches);
 		if ($result === 1) {
-			$data->setSwapTotal((int)$matches['Avail'][0]);
-			$data->setSwapFree($data->getSwapTotal() - (int)$matches['Used'][0]);
+			$data->setSwapTotal((int)($matches['Avail'][0] / 1024));
```
Comment (kesselb) [inline lib/OperatingSystems/FreeBSD.php:56]: swapinfo -k returns the values as KB. The conversion to bytes was missing here. Now they are correct.

**Review by ChristophWurst — APPROVED** [review]
